public class AddressRequest{
    public String[]  organization{get;set;}
    public String[]  department{get;set;}
    public String[]  contact{get;set;}
    public String[]  email{get;set;}
    public String[]  building{get;set;}
    public String[]  subBuilding{get;set;}
    public String[]  street{get;set;}
    public String[]  houseNumber{get;set;}
    public String[]  locality{get;set;}
    public String[]  preferredLocality{get;set;}
    public String[]  postalCode{get;set;}
    public String[]  province{get;set;}
    public String[]  country{get;set;}
    
}